server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Mybatis
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aaa

mybatis:
  type-aliases-package: com.lichen.mybatislearning.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: warn
    com.lichen: info
  file:
    path: /log/test.log
