server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Mybatis
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

mybatis:
  type-aliases-package: com.lichen.mybatislearning.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: warn
    com.lichen: info
  file:
    name: ./log/mybatis.log    # logging.file.name 的优先级要比 logging.file.path 的优先级更高，两个配置同时出现时不会一起生效。
